# https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
defaults: &defaults
  working_directory: ~/drush
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    TERM: dumb
    UNISH_NO_TIMEOUTS: y
    UNISH_DB_URL: mysql://root:@127.0.0.1
    PHPUNIT_ARGS: ""

version: 2
jobs:
  code_style:
    <<: *defaults
    docker:
      - image: wodby/php:7.1
        environment:
          - MYSQL_HOST=127.0.0.1
          - PHP_SENDMAIL_PATH=/dev/null
      - image: circleci/mysql:5.7.24
    steps:
      - checkout
      - run: cp .docker/zz-php.ini /usr/local/etc/php/conf.d/
      - run: composer install
      - run: composer cs

  test_71:
    <<: *defaults
    docker:
      - image: wodby/php:7.1
        environment:
          - MYSQL_HOST=127.0.0.1
          - PHP_SENDMAIL_PATH=/dev/null
      - image: circleci/mysql:5.7.24
    steps:
      - checkout
      - run: cp .docker/zz-php.ini /usr/local/etc/php/conf.d/
      - run: composer install
      - run: $HOME/drush/.circleci/patch.sh
      - run: composer lint
      - run: composer phpunit

  test_72_highest:
    <<: *defaults
    docker:
      - image: wodby/php:7.2
        environment:
          - MYSQL_HOST=127.0.0.1
          - PHP_SENDMAIL_PATH=/dev/null
      - image: circleci/mysql:5.7.24
    steps:
      - checkout
      - run: cp .docker/zz-php.ini /usr/local/etc/php/conf.d/
      - run: composer remove --dev webflo/drupal-core-strict --no-update
      - run: composer require --dev drupal/core:8.7.x-dev --no-update
      - run: composer config platform.php 7.2
      - run: composer update
      - run: composer functional

  test_56:
    <<: *defaults
    docker:
      - image: wodby/php:5.6
        environment:
          - MYSQL_HOST=127.0.0.1
          - PHP_SENDMAIL_PATH=/dev/null
      - image: circleci/mysql:5.7.24
    steps:
      - checkout
      - run: cp .docker/zz-php.ini /usr/local/etc/php/conf.d/
      - run: .scenarios.lock/install php5
      - run: $HOME/drush/.circleci/patch.sh
      - run: composer functional

workflows:
  version: 2
  drush:
    jobs:
      - code_style
      - test_71
      - test_72_highest
      - test_56
